title: Meng Wu
position: Incoming Ph.D. Student
affiliation: University of Michigan
affiliation_link: https://umich.edu/
email: wymond@umich.edu

keywords: Meng Wu, diffusion models, generative AI, computer vision, machine learning
description: Meng Wu is an incoming Ph.D. student at the University of Michigan studying generative models, representation learning, and computer vision.
canonical: https://mengvv.github.io/mengwu.github.io/

cv_link: ./assets/files/Meng_Wu_CV.pdf
github_link: https://github.com/mengVV
linkedin: https://www.linkedin.com/in/meng-wu

favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
enable_footnote: true
auto_dark_mode: false
font: "Sans Serif"

url: https://mengvv.github.io
baseurl: /mengwu.github.io
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - html_source_file/
